services:
  discord-bot:
    build: ./discord-bot/
    volumes:
      - ./discord-bot/.env:/home/node/app/.env
      - data:/etc/data
    environment:
      - EVENTS_DB_PATH=/etc/data/events_database.db
  upload-service:
    build: ./pyscraper/
    volumes:
      - ./discord-bot/.env:/usr/src/app/.env
      - data:/etc/data
    ports:
      - 80:5000
    environment:
      - STATIC_PATH=/etc/data/static
  cron:
    build:
      context: ./pyscraper
      dockerfile: Dockerfile.cron
    volumes:
      - ./discord-bot/.env:/usr/src/app/.env
      - data:/etc/data
    environment:
      - STATIC_PATH=/etc/data/static
      - EVENTS_DB_PATH=/etc/data/events_database.db
volumes:
  data:
