services:
  discord-bot:
    build: ./discord-bot/
    volumes:
      - ./discord-bot/.env:/home/node/app/.env
      - type: bind
        source: ./events_database.db
        target: /home/node/app/events_database.db
      - type: bind
        source: ./discord-bot/src
        target: /home/node/app/src
    environment:
      - EVENTS_DB_PATH=/home/node/app/events_database.db
  upload-service:
    build: ./pyscraper/
    volumes:
      - ./discord-bot/.env:/usr/src/app/.env
      - type: bind
        source: ./events_database.db
        target: /usr/src/app/events_database.db
    ports:
      - 80:5000
    environment:
      - IMAGES_PATH=/usr/src/app/static/uploads
      - EVENTS_DB_PATH=/usr/src/app/events_database.db
