FROM python:3.11.4-alpine

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY convert_stories_to_text.py events_db.py run_cron_job.sh ./

ADD crontab.txt ./crontab.txt
COPY entry.sh ./entry.sh
RUN chmod 755 ./run_cron_job.sh ./entry.sh
RUN /usr/bin/crontab ./crontab.txt
RUN touch /var/log/cron.log

CMD python events_db.py && ./entry.sh && tail -f /var/log/cron.log
